package presentacion;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import configuracion.Configuracion;
import configuracion.Genotipo_enum;
import configuracion.Mutacion_enum;
import configuracion.Reproduccion_enum;
import configuracion.Seleccion_enum;

/**
*
* @author carlo
*/
public class PanelInfo extends javax.swing.JPanel {
   
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private JFrame j;
	
   /**
    * Creates new form NewJPanel
    */
   public PanelInfo(JFrame j) {
       initComponents();
       this.j = j;
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   
   // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
   private void initComponents() {

       jTextFieldGeneraciones = new javax.swing.JTextField();
       jLabelSeleccion = new javax.swing.JLabel();
       jComboBoxSeleccion = new javax.swing.JComboBox<>();
       jLabelCruce = new javax.swing.JLabel();
       jComboBoxCruce = new javax.swing.JComboBox<>();
       jLabelCruceporcentaje = new javax.swing.JLabel();
       jTextFieldCruceporcentaje = new javax.swing.JTextField();
       jLabelProblema = new javax.swing.JLabel();
       jLabelPoblacion = new javax.swing.JLabel();
       jComboBoxProblemas = new javax.swing.JComboBox<>();
       jTextFieldPoblacion = new javax.swing.JTextField();
       jLabelGeneraciones = new javax.swing.JLabel();
       jButtonRun = new javax.swing.JButton();
       jLabelPrecision = new javax.swing.JLabel();
       jTextFieldError = new javax.swing.JTextField();
       jLabelProbMutacion = new javax.swing.JLabel();
       jTextFieldProbMutacion = new javax.swing.JTextField();

       setBackground(new java.awt.Color(187, 212, 238));

       jTextFieldGeneraciones.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
       jTextFieldGeneraciones.setToolTipText("Introduce el numero de generaciones (valor entero)");
       jTextFieldGeneraciones.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jTextFieldGeneracionesActionPerformed(evt);
           }
       });

       jLabelSeleccion.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
       jLabelSeleccion.setText("seleccion");

       jComboBoxSeleccion.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
       jComboBoxSeleccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ruleta", "Estocastica", "Truncamiento", "Torneo Deterministico",
    		   "Torneo Probabilistico"}));
       jComboBoxSeleccion.setToolTipText("Elige un mï¿½todo de seleccion");
       jComboBoxSeleccion.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jComboBoxSeleccionActionPerformed(evt);
           }
       });

       jLabelCruce.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
       jLabelCruce.setText("Cruce");

       jComboBoxCruce.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
       jComboBoxCruce.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Un punto", "Varios puntos", "Uniforme" }));
       jComboBoxCruce.setToolTipText("Selecciona un mecanismo de cruce");
       jComboBoxCruce.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
       jComboBoxCruce.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jComboBoxCruceActionPerformed(evt);
           }
       });

       jLabelCruceporcentaje.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
       jLabelCruceporcentaje.setText("Cruce %");

       jTextFieldCruceporcentaje.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
       jTextFieldCruceporcentaje.setToolTipText("Selecciona un porcentaje de cruce");
       jTextFieldCruceporcentaje.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jTextFieldCruceporcentajeActionPerformed(evt);
           }
       });

       jLabelProblema.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
       jLabelProblema.setText("Problema");

       jLabelPoblacion.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
       jLabelPoblacion.setText("Tamaï¿½o de la poblacion");

       jComboBoxProblemas.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
       jComboBoxProblemas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
       jComboBoxProblemas.setToolTipText("Selecciona el problema a resolver");

       jTextFieldPoblacion.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
       jTextFieldPoblacion.setToolTipText("Introduce el tamaï¿½o de la poblacion (valor entero)");
       jTextFieldPoblacion.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jTextFieldPoblacionActionPerformed(evt);
           }
       });

       jLabelGeneraciones.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
       jLabelGeneraciones.setText("Numero de generaciones");

       jButtonRun.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
       jButtonRun.setText("Run");
       jButtonRun.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
       jButtonRun.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButtonRunActionPerformed(evt);
           }
       });

       jLabelPrecision.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
       jLabelPrecision.setText("Precision");

       jTextFieldError.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
       jTextFieldError.setToolTipText("Selecciona un porcentaje de cruce");
       jTextFieldError.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jTextFieldErrorActionPerformed(evt);
           }
       });

       jLabelProbMutacion.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
       jLabelProbMutacion.setText("Prob Mutacion");

       jTextFieldProbMutacion.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
       jTextFieldProbMutacion.setToolTipText("Selecciona un porcentaje de cruce");
       jTextFieldProbMutacion.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jTextFieldProbMutacionActionPerformed(evt);
           }
       });

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
       this.setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(layout.createSequentialGroup()
                       .addContainerGap()
                       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addGroup(layout.createSequentialGroup()
                               .addComponent(jLabelPrecision)
                               .addGap(11, 11, 11)
                               .addComponent(jTextFieldError))
                           .addComponent(jComboBoxSeleccion, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                           .addGroup(layout.createSequentialGroup()
                               .addComponent(jLabelCruce)
                               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                               .addComponent(jComboBoxCruce, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                           .addGroup(layout.createSequentialGroup()
                               .addComponent(jLabelCruceporcentaje)
                               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                               .addComponent(jTextFieldCruceporcentaje))))
                   .addGroup(layout.createSequentialGroup()
                       .addContainerGap()
                       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                           .addComponent(jLabelPoblacion)
                           .addComponent(jLabelGeneraciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                           .addComponent(jTextFieldGeneraciones)
                           .addComponent(jTextFieldPoblacion)))
                   .addGroup(layout.createSequentialGroup()
                       .addGap(52, 52, 52)
                       .addComponent(jLabelSeleccion))
                   .addGroup(layout.createSequentialGroup()
                       .addGap(55, 55, 55)
                       .addComponent(jButtonRun))
                   .addGroup(layout.createSequentialGroup()
                       .addContainerGap()
                       .addComponent(jLabelProblema)
                       .addGap(10, 10, 10)
                       .addComponent(jComboBoxProblemas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                   .addGroup(layout.createSequentialGroup()
                       .addContainerGap()
                       .addComponent(jLabelProbMutacion)
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                       .addComponent(jTextFieldProbMutacion)))
               .addContainerGap())
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addContainerGap()
               .addComponent(jLabelPoblacion)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addComponent(jTextFieldPoblacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addComponent(jLabelGeneraciones)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addComponent(jTextFieldGeneraciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addComponent(jLabelSeleccion)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addComponent(jComboBoxSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGap(18, 18, 18)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(jLabelCruce)
                   .addComponent(jComboBoxCruce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(jTextFieldCruceporcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(jLabelCruceporcentaje))
               .addGap(11, 11, 11)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(jLabelPrecision)
                   .addComponent(jTextFieldError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGap(11, 11, 11)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(jLabelProbMutacion)
                   .addComponent(jTextFieldProbMutacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGap(18, 18, 18)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(jLabelProblema)
                   .addComponent(jComboBoxProblemas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGap(18, 18, 18)
               .addComponent(jButtonRun)
               .addContainerGap(76, Short.MAX_VALUE))
       );

       jComboBoxCruce.getAccessibleContext().setAccessibleDescription("Permite seleccionar el cruce");
   }// </editor-fold>                        

   private void jTextFieldGeneracionesActionPerformed(java.awt.event.ActionEvent evt) {                                                       
       // TODO add your handling code here:
   }                                                      

   private void jComboBoxSeleccionActionPerformed(java.awt.event.ActionEvent evt) {                                                   
       // TODO add your handling code here:
   }                                                  

   private void jComboBoxCruceActionPerformed(java.awt.event.ActionEvent evt) {                                               
       // TODO add your handling code here:
   }                                              

   private void jTextFieldCruceporcentajeActionPerformed(java.awt.event.ActionEvent evt) {                                                          
       // TODO add your handling code here:
   }                                                         

   private void jTextFieldPoblacionActionPerformed(java.awt.event.ActionEvent evt) {                                                    
       // TODO add your handling code here:
   }                                                   

   private void jButtonRunActionPerformed(java.awt.event.ActionEvent evt) {                                           
	   // TODO add your handling code here:
	   if(this.jTextFieldPoblacion.getText().isEmpty() || jTextFieldGeneraciones.getText().isEmpty()
			   || jTextFieldCruceporcentaje.getText().isEmpty() || jTextFieldError.getText().isEmpty()
			   || this.jTextFieldProbMutacion.getText().isEmpty()) {
		   JOptionPane.showMessageDialog(null,"Error: Faltan datos", "error", JOptionPane.ERROR_MESSAGE);
	   }
	   else {
		   int tamano_poblacion = Integer.parseInt(this.jTextFieldPoblacion.getText());
	       int num_generaciones = Integer.parseInt(this.jTextFieldGeneraciones.getText());
	       String seleccion = (String) this.jComboBoxSeleccion.getSelectedItem();
	       String cruce = (String) this.jComboBoxCruce.getSelectedItem();
	       //int cruceporcentaje = Integer.parseInt(this.jTextFieldCruceporcentaje.getText());
	       double cruceporcentaje =Double.parseDouble(this.jTextFieldCruceporcentaje.getText());
	       double precision =Double.parseDouble(this.jTextFieldError.getText());
	       //double precision = Integer.parseInt(this.jTextFieldError.getText());
	       //int prob_mutacion = Integer.parseInt(this.jTextFieldProbMutacion.getText());
	       double prob_mutacion =Double.parseDouble(this.jTextFieldProbMutacion.getText());
	       int problema = this.jComboBoxProblemas.getSelectedIndex();
	       //A partir de aquï¿½ no estï¿½ en NetBeans
	       Seleccion_enum s = getSeleccion(seleccion);
	       Reproduccion_enum r = getReproduccion(cruce);
	       Mutacion_enum m = getMutacion("");
	       
	       /*
	        * double minimo, double maximo, boolean maximizar,
			double precision, int num_parametros, int num_generaciones, double prob_mutacion,
			Reproduccion_enum r, Mutacion_enum m, Seleccion_enum s)
	        */
	       
	       if(true) {
	    	   Configuracion c = new Configuracion(true,precision,num_generaciones,
	    			   prob_mutacion,r,m,s, Genotipo_enum.Binario , problema ,cruceporcentaje, tamano_poblacion, 1);
	    	   Controlador controlador= new Controlador();
	    	   System.out.println("tamaño de la poblacion" + tamano_poblacion);
	    	   controlador.execute(c,j);
	    	   
	       }
	       else {
	    	   JOptionPane.showMessageDialog(null, "Error: Se han introducido datos erroneos","error", JOptionPane.ERROR_MESSAGE);
	       }
	   }
       
       
       
       //Configuracion c = new Configuracion()
   }                                          

   private void jTextFieldErrorActionPerformed(java.awt.event.ActionEvent evt) {                                                
       // TODO add your handling code here:
   }                                               

   private void jTextFieldProbMutacionActionPerformed(java.awt.event.ActionEvent evt) {                                                       
       // TODO add your handling code here:
   }                                                      

   private Seleccion_enum getSeleccion(String s) {
	   if(s.equalsIgnoreCase("Ruleta")) return Seleccion_enum.Ruleta;
	   else if (s.equalsIgnoreCase("Estocastica")) return Seleccion_enum.Estocastica;
	   else if (s.equalsIgnoreCase("Truncamiento")) return Seleccion_enum.Truncamiento;
	   else if (s.equalsIgnoreCase("Torneo Deterministico")) return Seleccion_enum.Torneo_Deterministico;
	   else if (s.equalsIgnoreCase("Torneo Probabilistico")) return Seleccion_enum.Torneo_Probabilistico;
	   else return null;
   }
   
   private Reproduccion_enum getReproduccion(String s) {
	   if(s.equalsIgnoreCase("Un punto")) return Reproduccion_enum.Un_punto;
	   else if (s.equalsIgnoreCase("Varios puntos")) return Reproduccion_enum.Varios_puntos;
	   else if (s.equalsIgnoreCase("Uniforme")) return Reproduccion_enum.Uniforme;
	   else return null;
   }

   private Mutacion_enum getMutacion(String s) {
	   return Mutacion_enum.Normal;
   }

   // Variables declaration - do not modify                     
   private javax.swing.JButton jButtonRun;
   private javax.swing.JComboBox<String> jComboBoxCruce;
   private javax.swing.JComboBox<String> jComboBoxProblemas;
   private javax.swing.JComboBox<String> jComboBoxSeleccion;
   private javax.swing.JLabel jLabelCruce;
   private javax.swing.JLabel jLabelCruceporcentaje;
   private javax.swing.JLabel jLabelGeneraciones;
   private javax.swing.JLabel jLabelPoblacion;
   private javax.swing.JLabel jLabelPrecision;
   private javax.swing.JLabel jLabelProbMutacion;
   private javax.swing.JLabel jLabelProblema;
   private javax.swing.JLabel jLabelSeleccion;
   private javax.swing.JTextField jTextFieldCruceporcentaje;
   private javax.swing.JTextField jTextFieldError;
   private javax.swing.JTextField jTextFieldGeneraciones;
   private javax.swing.JTextField jTextFieldPoblacion;
   private javax.swing.JTextField jTextFieldProbMutacion;
   // End of variables declaration                   
}
